### ISSUE TITLE
The checkbox for snapshot gets hidden by the loader version field when chosen

### ISSUE THREAD

**Issue by liach** [FabricMC/fabric-installer#10]
![image](https://user-images.githubusercontent.com/7806504/57416923-28dc7080-71b7-11e9-9214-2a8483a0ac13.png)
The situation is worse in root localization, where the checkbox will be completely invisible (but still can be clicked by clicking slightly above "Loader version")

I don't know what is the best way to resolve this.
Should we prevent long version names from pushing the checkbox to a new line, or put the checkbox on a new line?

**Comment by Prospector** [comment]
I'd say just make the window a bit bigger lol

**Comment by modmuss50** [comment]
That’s not really a solution due as another Lang could come along that requires more space.

**Comment by liach** [comment]
My suggestion is to prevent the drop-down box from adjusting size when long snapshot option names are added.

**Comment by modmuss50** [comment]
This was fixed a long while ago.
