### ISSUE TITLE
Installer fails on Android

### ISSUE THREAD

**Issue by PseudoDistant** [FabricMC/fabric-installer#115]
JVM: OpenJDK 17 21-09-14
OS: Android 12.1 (Moto G 5G)
![Screenshot_20221119-115916](https://user-images.githubusercontent.com/67613281/202862849-344749b9-731b-4e6a-8021-d4f7eddcc862.png)

It no workie

**Comment by modmuss50** [comment]
This doesnt look like an issue with the installer as its unable to find a window server to disable the UI, does the vanilla even launcher work? Let alone the game. This isnt a platform we support.

**Comment by modmuss50** [comment]
Ok, I'll leave this one to Player then, I dont use or know anything about Andorid.

**Comment by sfPlayer1** [comment]
IMO it is a case of flawed X11 detection in AWT (isHeadless) that may be applicable more broadly, was thinking about just adding a try catch.

**Comment by unix-supremacist** [comment]
> It's basically just a trimmed down Linux environment.

not exactly android has a ton of small issues that could become problematic like patches for any software over the regular linux kernel, a non complete libc, etc though i don't know which of these would effect something as sandboxed as java applications.

this seems to be what player said, it trying to use x11 that android doesn't have no?

**Comment by unix-supremacist** [comment]
> There are apps on Google Play that run an X11 server, and an app for Wayland.

i'm aware i was just talking about base android, not installing a ton of third party stuff for it, you can get x11 servers on windows and reactos lol

**Comment by modmuss50** [comment]
Whats the use case for running the fabric installer on andorid? I was unware that the MC launcher, and MC its self ran on it. (Again I know there are 3rd party tools do this, that already support fabric).

**Comment by modmuss50** [comment]
If you cannot run Minecraft I dont see why you want to run the fabric installer? Chrome OS sounds like a more reasonable platform to support.

**Comment by modmuss50** [comment]
You shouldnt be using the GUI installer for servers anymore, try the server launcher from: https://fabricmc.net/use/server/

**Comment by modmuss50** [comment]
I guess you can also use the installer CLI, but for a server I hightly reccomend using the server launcher I linked above.

Its the same installer just pre configured for a specific version.

**Comment by modmuss50** [comment]
Closing this as there is nothing I can do about it. Please make a PR if you are able to fix this, or use the CLI version.
