### ISSUE TITLE
Fabric Installer crashes when I try to pick a folder

### ISSUE THREAD

**Issue by Eatham532** [FabricMC/fabric-installer#126]
[hs_err_pid3360.log](https://github.com/FabricMC/fabric-installer/files/13345608/hs_err_pid3360.log)

There isn't much else to say here. Hopefully the logs help

**Comment by modmuss50** [comment]
This might sound odd, but do you have a "God Mode" shortcut on your desktop or another location? These special folder names are actually called "Junction Points", and cause a crash in Java 8 or 9.

See the JDK bug about this here: https://bugs.openjdk.org/browse/JDK-8179014

The installer is being launched using Java 8, however I do also see that you have Java 17 and 11 installed, and Java 17 is set as you JAVA_HOME version, whats intresting is our installer bootstrap should be using JAVA_HOME before trying to use java from the path 🤔

**Comment by Eatham532** [comment]
Surprisingly yeh, I do have God Mode. That is really odd that Java 8 does that. (Don't have 9)

**Comment by modmuss50** [comment]
Going to close this as there isnt anything we can do to fix it. Running the installer with a newer Java is a sutible fix.
