### ISSUE TITLE
Set jar manifest to allow native code in preperation for restricted JNI use.

### ISSUE THREAD

**Issue by modmuss50** [FabricMC/fabric-installer#139]
In a future Java version JNI/native code will be opt in via a launch option. As the installer is commonly ran by double clicking a .jar we will no longer be able to use native code.

~~A work around will be to fork a new JVM process.~~ Set a manifest entry

See: https://openjdk.org/jeps/472

**Comment by Juuxel** [comment]
The JEP also talks about a manifest entry that seems useful in this situation:
> You can add `Enable-Native-Access: ALL-UNNAMED` to the manifest of an executable JAR file, i.e., a JAR file that is launched via `java -jar`. (`ALL-UNNAMED` is the only supported value for the `Enable-Native-Access` entry. Other values cause an exception to be thrown.)

**Comment by modmuss50** [comment]
Oh right, that solves the problem! I should learn to read lol. Thanks
