### ISSUE TITLE
The png icon used to create the profile icon has too much extra "something" in it

### ISSUE THREAD

**Issue by calloatti** [FabricMC/fabric-installer#23]
The png file https://github.com/FabricMC/fabric-installer/blob/master/src/main/resources/profile_icon.png has extra data in it that I have no idea what it is, making the launcher_profiles.json file bloated 

![image](https://user-images.githubusercontent.com/12817862/60616515-08402980-9da8-11e9-95e3-e3e4d1e1dfad.png)
![image](https://user-images.githubusercontent.com/12817862/60616581-30c82380-9da8-11e9-9138-4626dd602ec8.png)

Fixed png just by opening it in a sane image editor and saving again:

![image](https://user-images.githubusercontent.com/12817862/60616643-56edc380-9da8-11e9-86c3-fea3bf9e7459.png)

**Comment by asiekierka** [comment]
>sane image editor

Just use optipng...
