### ISSUE TITLE
installer always downloads a 0kb jar file

### ISSUE THREAD

**Issue by luvletter2333** [FabricMC/fabric-installer#24]
finally I found a jar file in maven `https://maven.fabricmc.net/net/fabricmc/fabric-loader/0.4.8%2Bbuild.159/`

**Comment by modmuss50** [comment]
I think this is intended:

https://github.com/FabricMC/fabric-installer/blob/master/src/main/java/net/fabricmc/installer/client/ClientInstaller.java#L47-L56

Is it not working?

**Comment by luvletter2333** [comment]
but the official launcher recognize the fabric.
maybe it's a permission problem? but the json file is intact

**Comment by luvletter2333** [comment]
Not a permission problem. I run it as administrator,but it still gives me a 0kb jar file.

**Comment by luvletter2333** [comment]
oh sorry. i know it.
