### ISSUE TITLE
Exe installer does not detect OpenJDK as a valid Java installation

### ISSUE THREAD

**Issue by Shnupbups** [FabricMC/fabric-installer#26]
I can't open the Fabric Installer .exe as it tells me 'This application requires a Java Runtime Environment 1.8.0' despite being able to run the .jar version perfectly fine. I have OpenJDK's JRE 11.0.4.11 installed.

**Comment by SkilledTheGamer** [comment]
can you try to install java's jre?
i think that would help or not

**Comment by Shnupbups** [comment]
Well yeah, of course that would help.

**Comment by modmuss50** [comment]
Not sure what I can do to fix this, is it a Launch4J issue?

**Comment by florensie** [comment]
Same issue. I have AdoptOpenJDK 8 and GraalVM 8 installed through scoop.

**Comment by comp500** [comment]
Launch4j seems to use the windows registry to look for Oracle JVM entries rather than JAVA_HOME, so it's an issue with launch4j.

**Comment by modmuss50** [comment]
I have updated Launch4j, I wonder if its better now?

**Comment by comp500** [comment]
Still doesn't seem to find AdoptOpenJDK (installed through scoop) with 0.6.0.42.

**Comment by comp500** [comment]
Found https://sourceforge.net/p/launch4j/feature-requests/127/, apparently it's a known issue but hasn't been fixed yet. You may be able to work around this by specifying %JAVA_HOME% as the JRE path in the config.xml - see https://sourceforge.net/p/launch4j/bugs/197/#d574. This solution might break other things that set the registry entry and don't set %JAVA_HOME% though...

**Comment by modmuss50** [comment]
This issue seems resolved on launch4j's side of things. I will look into updating it soon.

**Comment by modmuss50** [comment]
This has now been resolved.

**Comment by leehuer** [comment]
hey i got those issue too but they gave that and i followed that link seems like someone who talking to each other,  and the regedit key so what i should now or just copy and started with editing the version of openJDK than save and add it?
