### ISSUE TITLE
Option to download fabric api after installing the game

### ISSUE THREAD

**Issue by liach** [FabricMC/fabric-installer#29]
Since many fabric mods need the fabric api (though not all), we can have an option to download fabric api to a server install location or a fabric client launcher profile. That can save people from downloading the fabric api.

**Comment by modmuss50** [comment]
The first issue I see is we dont have a reliable way to map fabric api versions to the correct mc version.

**Comment by modmuss50** [comment]
No, the issue is I just dont have the data to pipe into that.

**Comment by modmuss50** [comment]
A message has been added.
