### ISSUE TITLE
Potential Fabric installation issue

### ISSUE THREAD

**Issue by Troublebrew** [FabricMC/fabric-installer#32]
hello, both my friend and i have run into an issue with the installation of Fabric 1.15.1 with default options
i managed to fix it myself just by toying around. However, my friend and i have discovered that there seems to be a chance the freshly installed Fabric 1.15.1 on default options may not be properly playable when launched thru the default Minecraft launcher, and crash once past the Mojang loading screen.

**Comment by Earthcomputer** [comment]
Can you post the crash log?

**Comment by Troublebrew** [comment]
i'll have my friend send his crash log

**Comment by Troublebrew** [comment]
it would just be a normal minecraft crash log, right?

**Comment by Troublebrew** [comment]
alright, i think these log files are the ones you're wanting
i have a third one with Out Of Memory error, which im pretty sure was me doing stupid stuff on minecraft.
[.log](https://github.com/FabricMC/fabric-installer/files/4009716/default.log)
[hs_err_pid16072.log](https://github.com/FabricMC/fabric-installer/files/4009717/hs_err_pid16072.log)

**Comment by Troublebrew** [comment]
[launcher_log.txt](https://github.com/FabricMC/fabric-installer/files/4009724/launcher_log.txt)
this was the only log he could find. is it what you need?

**Comment by Troublebrew** [comment]
[launcher_log.txt](https://github.com/FabricMC/fabric-installer/files/4009731/launcher_log.txt)
i read thru his launcher log that he sent to me
it appears to have a problem with one of his 1.12.2 jars

**Comment by Earthcomputer** [comment]
You should run the game in a different directory for different modpacks

**Comment by Troublebrew** [comment]
we're not exactly trying to run a modpack
we're just trying to run fabritone, voxelmaps, and fabric api

**Comment by Earthcomputer** [comment]
That's a pack of three mods, and it seems to be clashing with some 1.12.2 jars like you say. Try using a separate directory and see if it fixes it.

**Comment by Troublebrew** [comment]
alright, i'll tell my friend that

**Comment by Troublebrew** [comment]
alright, so by separate directory you mean to install the Fabric-Loader-1.15.1 somewhere other than appdata?

**Comment by Earthcomputer** [comment]
You've already installed fabric loader - in the Minecraft launcher you can edit your fabric profile and change the game directory

**Comment by Troublebrew** [comment]
so, i can just change this to like the junk folder on my desktop?

**Comment by Troublebrew** [comment]
alright, my friend tried setting the directory to appdata>>roaming>>.fabric
didnt work
i told him to try just using his desktop
said he cant use it

**Comment by Troublebrew** [comment]
well, Fabric-Loader-1.15.1 works for me with VoxelMaps and Fabric API
so im thinking the Fabritone is not working well

**Comment by Troublebrew** [comment]
yep, that fixed it

**Comment by Troublebrew** [comment]
it's an issue with Fabritone

**Comment by Troublebrew** [comment]
im not sure he's gonna be too fond of that, he likes baritone
