### ISSUE TITLE
Fabric installer has crashed!

### ISSUE THREAD

**Issue by kookoodaayoo** [FabricMC/fabric-installer#36]
![IMG_20200502_072517](https://user-images.githubusercontent.com/64960229/81284786-285c0b80-9091-11ea-93ab-5e49adb33565.jpg)
   I was unable to open the fabric installer in Java       
   Is there any solution to this problem

**Comment by Yanis48** [comment]
Seems to be your connection

**Comment by kookoodaayoo** [comment]
> 似乎是您的联系
I was lucky enough to open it once and then it didn't work. I don't know why

**Comment by liach** [comment]
嗯，网不好的确可怜，试试看找个加速器VPN吧

**Comment by modmuss50** [comment]
Closing as this isnt an issue with the installer.
