### ISSUE TITLE
In Windows, Using the installer with the Minecraft Launcher open can lead to silent install failure

### ISSUE THREAD

**Issue by calloatti** [FabricMC/fabric-installer#41]
If a default Client install is done while the Minecraft launcher is open, it could lead to the profile not being created.

![](https://user-images.githubusercontent.com/12817862/86288493-61f85100-bbc0-11ea-9fe3-95638215125b.png)

If after performing a default client install with the Minecraft Launcher open, the Minecraft Launcher is restarted, the profile created by the Fabric installer will show up in the list of Installations.

Any changes to the configuration of any of the "Installations" done in the Minecraft Launcher after performing a default client install, or creating a new "Installation" manually on the Minecraft Launcher will overwrite the changes to launcher\_profiles.json done by the Fabric Installer.

It seems the Minecraft launcher writes the changes on exit (for simple changes) and immediately when creating a new profile, in both cases overwriting the changes made by the Fabric Installer.

Another problem is that a user may expect that the profile created by the Fabric installer will show up the the Installations list automatically without the need to restart the Minecraft Launcher.

solution 1: The Fabric installer should detect that the Minecraft Launcher is open and warn the user to close it before proceeding. 

solution 2: A simple message box warning the user to close the Minecraft Launcher, without performing any detection.

**Comment by liach** [comment]
Personally I'd suggest installer ask users to manually close. There may be variants of installer and don't think it's that easy to detect other running applications in java.

**Comment by modmuss50** [comment]
The big question here is how to detect that the launcher is open?

**Comment by DeathsGun** [comment]
@modmuss50 does the solution need to be compatible with java 8?

**Comment by modmuss50** [comment]
Yes, the installer target's java 8

**Comment by DeathsGun** [comment]
That's a problem because java 9 has an new API which would allow this functionality: https://stackoverflow.com/a/45068036

**Comment by modmuss50** [comment]
A warning is now shown: https://github.com/FabricMC/fabric-installer/commit/4633147fcbce9be77e1d68b06d454c0ae896ba5f
