### ISSUE TITLE
0.4.0.18 launcher crashes on startup

### ISSUE THREAD

**Issue by AK9Official** [FabricMC/fabric-installer#5]
Fabric Loader: 0.4.4 build 137
Yarn: 1.14 Build 3

Crash Report: https://pastebin.com/GmhT0JNz

Don't hate me Asie -_-

**Comment by asiekierka** [comment]
[Fixed.](https://github.com/FabricMC/fabric-loader/commit/9a1981339f1bbc5f50bf7382927417108cb6fdb5)
