### ISSUE TITLE
Versioned mods folder

### ISSUE THREAD

**Issue by velnias75** [FabricMC/fabric-installer#53]
I hope this is the right repo.

It would be nice to have versioned `mods` folders, i.e. `mods.1.16.3` for the _Minecraft_ version 1.16.3.

Most mods are version dependent and it can be a mess to rename all the jar files if someone needs to switch the versions in the _Minecraft launcher_.
If **Fabric** would just create and use an own `mods` folder for each version it could be more simple to handle.

**Comment by JamiesWhiteShirt** [comment]
This has been discussed many times before, both on GitHub and Discord. Here is a [related issue on Fabric Loader](https://github.com/FabricMC/fabric-loader/issues/181).

The idea of having a versioned mods folder implies the re-use of a minecraft installation across multiple versions of the game, which is rarely a good idea. Using the same installation means you will share worlds and settings between all the versions. These files may not be cross-compatible between the versions, therefore it is not recommended. 

The recommended method of installing multiple versions of the game with their own mods is to use multiple installations, each with its own mods directory. The Minecraft launcher already supports this.

Also note that renaming jar files is never required to make mods work with specific versions of the game. If you are changing file extensions to disable mods, I would suggest maintaining multiple directories and moving/copying the mods between them instead.

**Comment by velnias75** [comment]
Duplicate of https://github.com/FabricMC/fabric-loader/issues/181
