### ISSUE TITLE
Fabric installer break profiles with accent names

### ISSUE THREAD

**Issue by vico93** [FabricMC/fabric-installer#55]
I used `0.6.1.51` to install the latest loader and after that all profiles having accents in its names (like `Versão 1.16` for a 1.16 profile) swaped with ideogram characters:
![image](https://user-images.githubusercontent.com/3485505/95147039-f0e3af00-0755-11eb-8432-b09b67478377.png)

**Comment by modmuss50** [comment]
Are you able to try again with 0.7? This has hopefully been fixed.

**Comment by vico93** [comment]
I hope someone could test it, since i'm not using Fabric anymore.

**Comment by modmuss50** [comment]
I’ll close it as I’m fairly certain this has been fixed.
