### ISSUE TITLE
Proposal: Fabric Hub - A cross-platform java based desktop application that installs fabric, and managing Fabric API installs

### ISSUE THREAD

**Issue by px01tv** [FabricMC/fabric-installer#62]
Fabric Hub is a cross-platform java based desktop application that installs fabric, and managing Fabric API installs

This could replace the old installer entirely and add new features, meaning that users never need to go to [fabricmc.net](https://fabricmc.net) to redownload the installer to get the latest fabric (most users delete the jar or leave it to rot in their downloads folder). With improved fresh UI, speed and command line support.

### UI Prototype

Made in Adobe XD with the Bootstrap library. Meaning it can be easily transferred to JavaFX, JavaFX has a bootstrap-like library available here: https://github.com/kordamp/bootstrapfx

![Main](https://user-images.githubusercontent.com/78348979/108127920-e2ae8380-70a3-11eb-8c89-593429d83bc7.png)

*Image is a placeholder, a showcase of fabric mods could be used though.*

*Read More would redirect the user to the news tab, where the article would be opened full screen.*

*GitHub and discord links can be added to the sidebar, but have been excluded in the design as Adobe XD prohibits external links, for now, be imaginative and imagine a github and discord icon at the bottom of the sidebar, under the version info.*

*Options can be added to the Install Fabric area, i couldn't think of any others from the top of my head.*

### CLI Idea

```cmd
$ fabric install 1.16.5 0.11.1 --with-api=0.30.0
Installing fabric.
Located minecraft installation!
Downloading... (100%)
Installing...
Installed fabric-loader-0.11.1.jar
Downloading Fabric API... (100%)
Moving to mods folder...
Added fabric-api-1.16-0.30.0.jar to mods folder.

Done! Installed fabric in 2553ms!
```

### Spec

- Cross Platform 
- Gradle
- JavaFX 11
- jpackage 
- jlink
- BootstrapFX for UI

**Comment by px01tv** [comment]
If someone could put the feature label, that would be fab

**Comment by YTG1234** [comment]
> desktop application that manages your Fabric installations

Sounds like MultiMC to me!

-----
Okay, so. This hub that you're proposing will not only manage FabricMC installations but will also show the latest news (and possibly GitHub release feeds?)

I am a MultiMC user, and I want a reason to actually use this. Installing Fabric in the vanilla launcher is, of course, the main part of what this application does, and so I suggest the application be distributed in several modules (e.g. installation module, news module etc.)

By default, when installing the application, it will install all the modules. Let's assume that people that use MultiMC actually know what they're doing and can delete files (I know I'm overestimating Minecraft players, but let's just assume). The modules could be physical JAR files in a `modules` folder, maybe they should be named plugins? If a user does not want the Fabric installation module, they can just delete it. Less disk space, less bloat, everyone's happy.

Also, making sure that the app doesn't silently eat all of the host machine's resources is incredibly important as usually you'd leave it open in the background, which will affect other system processes.

**Comment by px01tv** [comment]
> Okay, so. This hub that you're proposing will not only manage FabricMC installations but will also show the latest news (and possibly GitHub release feeds?)

Yep! 

> desktop application that manages your Fabric installations

I should rephrase that to: "desktop application that installs Fabric and Fabric API"

Let me do some quick edits 😅

**Comment by px01tv** [comment]
@YTG1234 Cleared some things up.

**Comment by YTG1234** [comment]
A map of Minecraft <-> FAPI versions would have to be established in order for this to work. AFAIK it's been in the works for some time, idk when/if it will be out fully.

Although with your prototype it looks like the user needs to select a specific FAPI version manually, which would circumvent that to a certain extent.

**Comment by px01tv** [comment]
> 
> 
> A map of Minecraft <-> FAPI versions would have to be established in order for this to work. AFAIK it's been in the works for some time, idk when/if it will be out fully.
> 
> Although with your prototype it looks like the user needs to select a specific FAPI version manually, which would circumvent that to a certain extent.

Doesn't the fabric meta API exist for this?

**Comment by YTG1234** [comment]
> Doesn't the fabric meta API exist for this?

Meta works well for loader versions, but not for FAPI versions.

**Comment by px01tv** [comment]
Ah okay, i'm sure i can use the github API to automatically link FAPI versions with MC versions.

**Comment by px01tv** [comment]
> A map of Minecraft <-> FAPI versions would have to be established in order for this to work. AFAIK it's been in the works for some time, idk when/if it will be out fully.

Until ^ is completed.

**Comment by Technici4n** [comment]
Sounds like a ton of work for no benefit... Just use MultiMC?

**Comment by DeltaNedas** [comment]
Making multimc install the latest Fabric API for the installed fabric loader would be much easier than a separate installer program.

**Comment by px01tv** [comment]
This isn't multimc, it doesn't launch minecraft! Its a replacement for the fabric-installer! Anyways im closing.
