### ISSUE TITLE
[Request] Permission to use fabric-installer in project

### ISSUE THREAD

**Issue by Griefed** [FabricMC/fabric-installer#63]
Hello everyone,

I am writing a program in Java for creating serverpacks for any given Minecraft modpack, and am currently in the process of wanting to include an automatic Fabric installation. For said installation, I would like to use `fabric-installer` as a library, for installing Fabric.
The project in question is my [ServerPackCreator](https://github.com/Griefed/ServerPackCreator). The goal of said program is to make the life of Modpack makers a little easier (mine included, because creating serverpacks is always kind of time consuming. So, I want to make that part a little easier and less time consuming. For me and whoever wishes to use my program)

May I have your permission to use `FabricMC/fabric-installer` as a libary(dependency) in my project for installation of a Fabric server?

Cheers,
Griefed

**Comment by Technici4n** [comment]
I'm pretty sure you are allowed per the Apache 2.0 license.

**Comment by Griefed** [comment]
I thought as much, but wanted to ask first, anyway. Seemed like the right thing to do.

**Comment by modmuss50** [comment]
Yes, thats fine. If you find something is missing feel free to open another issue.
