### ISSUE TITLE
Fix Discord Compatibility by adding dummy class name

### ISSUE THREAD

**Issue by rizecookey** [FabricMC/fabric-installer#65]
As of right now, running Minecraft with the Fabric Loader will not be picked up by Discord (and other programs like the GeForce Experience Overlay) as a game unlike in vanilla, therefore preventing you from using the overlay etc. correctly. This, however, can be fixed by adding a dummy main class string to the game argument array inside the version's .json file. Since Discord (and most other programs trying to interact with Minecraft) only check if the string "net.minecraft.client.main.Main" (vanilla's main class) is present somewhere in the passed arguments, adding said string to the argument array fixes the problem.

**Comment by i509VCB** [comment]
I'm guessing a simple `-DFoolOtherProcessesToLetThemKnowMCIsBeingRun=net.minecraft.client.Main` would do it?

**Comment by rizecookey** [comment]
Yeah, that seems to work (it's `net.minecraft.client.main.Main` though, not `net.minecraft.client.Main`).

**Comment by modmuss50** [comment]
This really isnt something we should need to handle, might be worth opening a bug on the mc launcher? or reporting to discord?

**Comment by modmuss50** [comment]
This was fixed a few months back, by a meta update.
