### ISSUE TITLE
Include a java version (16) notice for installing minecraft 1.17 fabric servers

### ISSUE THREAD

**Issue by liach** [FabricMC/fabric-installer#74]
From https://github.com/FabricMC/fabric/issues/1487. The feasibility of this feature is somewhat debatable, though.

**Comment by haykam821** [comment]
If this feature is still necessary in addition to FabricMC/fabric-loader#438, we can reuse the same method there to dynamically determine whether the Java version used to run the launcher is outdated for a given Minecraft version.

**Comment by modmuss50** [comment]
No, I think this is fine just being in fabric loader.
