### ISSUE TITLE
Auto generate mods folder

### ISSUE THREAD

**Issue by bxvcd-732** [FabricMC/fabric-installer#89]
It is very small feature, but it can be really useful. Some people don't know where mods folder is located, and they don't know how to make mods folder. It can be useful for them, or for everyone.

**Comment by sfPlayer1** [comment]
Good idea, we may also want to add a bit of text ("install mods by putting their jar files into the mods folder") and a button to open it.

**Comment by modmuss50** [comment]
This was done. 👍
