### ISSUE TITLE
Installer generates fabric-server-launcher.jar without contents

### ISSUE THREAD

**Issue by slicedlime** [FabricMC/fabric-installer#97]
Versions 0.10.x of the installer seems to generate "empty" launch jars for me. I tried versions 0.10.2 and 0.10.1 of .exe installer. Downgrading to 0.9.1 works - I then get a proper launch jar.

The jar I get from 0.10.x contains only a .properties file and a meta-inf with a manifest.

Attaching the resulting jar renamed to zip.

[fabric-server-launch.zip](https://github.com/FabricMC/fabric-installer/files/7697264/fabric-server-launch.zip)

**Comment by sfPlayer1** [comment]
This works as intended, the jar is now nothing more than a way to populate the class path and provide main class references through standard java UrlClassLoader behavior, as well as configuring Fabric Loader as before. The installer puts the actual files into the `libraries` folder, which the almost-empty jar uses. It is important to copy `libraries` along with the usual `fabric-server-launcher.jar`, the vanilla `server.jar` and `fabric-server-launcher.properties` to an eventual remote host.

We're almost done releasing a new server installation method that is both single jar and launch-through.
