### ISSUE TITLE
New update from microsoft break profile

### ISSUE THREAD

**Issue by FlashLight34** [FabricMC/fabric-installer#98]
![Inkedfabric bug](https://user-images.githubusercontent.com/9997676/146595264-7c2721ab-1fbb-426b-ae76-792f53af5522.jpg)

`SET file=fabric-installer-0.10.2.jar
IF %newlauncher% EQU 1 (
  echo. Démarrage de l'installeur fabricmc Microsoft...
  echo.
  rem microsoft_store
  java -jar %file% client -dir %installdir% -mcversion %mcvers% -launcher microsoft_store
)
IF %newlauncher% EQU 0 (
  echo. Démarrage de l'installeur fabricmc...
  echo.
  java -jar %file% client -dir %installdir% -mcversion %mcvers% -launcher win32
)`

**Comment by FlashLight34** [comment]
i tried with win32 i got the same thing :(

**Comment by FlashLight34** [comment]
**_lundi 13 décembre 2021_**

**Tweaks and improvements**

_**1. Fixes & updates to how New Windows Launcher manages mods & save files.**_

2. Fixed bug where if you clicked "Add Account" & quickly closed the login window, you would see an error message. That shouldn't happen anymore.

3. Improvements to post-Microsoft Account migration flow.

4. Update for Dungeons Cloudy Climb event.

5. Corrected Minecraft logo art here and there throughout the Launcher.

6. Users new to Java will now be prompted to create a Java gamertag when they navigate to the Skins Java tab.

**Comment by modmuss50** [comment]
I am using this version of the launcher and cannot see any issues? I am unsure what has changed, and even if that is related to Minecraft or Dungeons?

What issue are you experiencing as it seems to be working fine for me?

**Comment by FlashLight34** [comment]
minecraft when i try to install, i dont have any fabric installation.

![image](https://user-images.githubusercontent.com/9997676/146580882-ab44ae02-bb96-4e49-ab7d-848f0c897b9e.png)

**Comment by FlashLight34** [comment]
with this `java -jar %file% client -mcversion %mcvers% -launcher microsoft_store` without -dir %installdir% i got this
![image](https://user-images.githubusercontent.com/9997676/146591947-87cd7885-8a33-4d5b-b4a6-afad086ec66f.png)

**Comment by FlashLight34** [comment]
Im on windows 11 sorry i try to be more clear than possible hehe

**Comment by FlashLight34** [comment]
what i can see the two launcher use the same profiles json now
![launcher bug](https://user-images.githubusercontent.com/9997676/146648105-feea4dfa-416f-4f7d-ae99-2c91f3a1c8f1.png)

**Comment by FlashLight34** [comment]
ok when i copy my profile file launcher_profiles.json and rename the copy to launcher_profiles_microsoft_store.json
that remove my error, but the problem is the new launcher not use this file anymore and delete him :(

**Comment by FlashLight34** [comment]
hello :P
i fixed my installer like this

in a .bat file
>SET launcherProfile_MC=%appdata%\.minecraft\launcher_profiles_microsoft_store.json
SET launcherProfile=%appdata%\.minecraft\launcher_profiles.json
IF NOT EXIST %launcherProfile_MC% (
 copy %launcherProfile% %launcherProfile_MC% /Y
)
 java -jar fabric-installer-0.10.2.jar client -mcversion 1.18.1 -launcher microsoft_store
IF EXIST %launcherProfile_MC% (
  rem save file before open launcher
  copy %launcherProfile_MC% %launcherProfile% /Y
  ping 127.0.0.1 -n 2 > nul
)
open launcher...

**Comment by FlashLight34** [comment]
i got this bug only with the Command line format, with the GUI that work fine.

**Comment by FlashLight34** [comment]
this bug exist if i use -dir with old launcher, i got this with my wife minecraft :| and if i dont use -dir no error but the profile is not created ...

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
